//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BordaAlgorithm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borda_Point
    {
        public long Uniq { get; set; }
        public string Main_Priority { get; set; }
        public string Second_Priority { get; set; }
        public string Third_Priority { get; set; }
        public string Fourth_Priority { get; set; }
        public string Fifth_Priority { get; set; }
    }
}
