//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BordaAlgorithm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBBordaAlgorithmEntities : DbContext
    {
        public DBBordaAlgorithmEntities()
            : base("name=DBBordaAlgorithmEntities")
        {
        }

        public static DBBordaAlgorithmEntities Create()
        {
            return new DBBordaAlgorithmEntities();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Career_List> Career_List { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Laptop> Laptops { get; set; }
        public virtual DbSet<Laptops_Brand_List> Laptops_Brand_List { get; set; }
        public virtual DbSet<Borda_Subject_List> Borda_Subject_List { get; set; }
        public virtual DbSet<Borda_Point> Borda_Point { get; set; }
        public virtual DbSet<Data_Survey> Data_Survey { get; set; }
    }
}
