//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BordaAlgorithm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laptop
    {
        public long Uniq { get; set; }
        public string Laptop_Brand { get; set; }
        public string Laptop_Type { get; set; }
        public double LCD_Height { get; set; }
        public double LCD_Width { get; set; }
        public double Ram_Capacity { get; set; }
        public double Memory_Capacity { get; set; }
        public double Processor_Speed { get; set; }
        public string Processor_UOM { get; set; }
        public string Currency { get; set; }
        public double Price { get; set; }
        public string Laptop_Image { get; set; }
        public string Remarks { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Edit_By { get; set; }
        public Nullable<System.DateTime> Edit_Date { get; set; }
        public string Delete_By { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public Nullable<bool> Is_Deleted { get; set; }
    }
}
